User.create( [{ name: "sujeev"}, { name: "sajith"}, { name: "viraj"}])
sports = Sport.create( [ {name: "tennis"}, { name: "basketball"}, { name: "football"}, { name: "vollyball"}])
Court.create( name: "t1", sport: sports.first)
Court.create( name: "t2", sport: sports.first)
Court.create( name: "b1", sport: sports.second)
Court.create( name: "b2", sport: sports.second)
